---
apiVersion: v1
kind: Pod
metadata:
  name: test-client-pod
spec:
  containers:
  - name: test-client-pod
    image: client-pod:0.1
    command: ["/bin/sh"]
    args: ["-c", "while true; do echo ==client ready==; sleep 20; done;"]
  dnsPolicy: ClusterFirst


